---
title: "Machine Learning (Iris)"
output: html_document
date: "2025-04-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the Raw Dataset

```{r load_data}
library(nnet)
cat("Original Fisher's Iris data:\n\n")
origdf<-read.table("D:/Probability and Statistics/demo_week1/IrisData.txt", 
                   header = TRUE, sep = ",")
write.table(origdf[1:2,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("...\n")
write.table(origdf[51:52,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("...\n")
write.table(origdf[101:102,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("\n")
```

## Factorize Data

```{r column}
col1<-origdf$Sepal.length
col2<-origdf$Sepal.width
col3<-origdf$Petal.length
col4<-origdf$Petal.width
col5<-factor(c(rep("s",50),rep("c",50),rep("v",50)))
irisdf<-data.frame(col1, col2, col3, col4, col5)
names(irisdf)<-c("SepLen", "SepWid","PetLen","PetWid","Species")
cat("Factorized data:\n\n")
write.table(irisdf[1:2,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("...\n")
write.table(irisdf[51:52,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("...\n")
write.table(irisdf[101:102,], col.names = TRUE, sep = "\t", quote = FALSE)
cat("\n")
```

## Configure the Training Sample

```{r training_sample}
set.seed(123)
sampidx<-c(sample(1:50,10),sample(51:100,10),sample(101:150,10))
cat("The training sample indices are:\n\n")
print(sampidx)
```

## Create and Train NN

```{r NN}
cat("\nCreating and training a neural network..\n")
mynn<-nnet(Species~SepLen+SepWid+PetLen+PetWid, data=irisdf, subset = sampidx,
           size=2, decay=1.0e-5, maxit=50)
```

## Evaluate the Accuracy of NN Model with a Confusion Matrix

```{r evaluate_model}
actual<-irisdf$Species[-sampidx]
preds<-predict(mynn, irisdf[-sampidx,], type = "class")
cm<-table(actual, preds)
cat("\nConfusion matrix for resulting nn model is..\n")
print(cm)
```

## Make a Single Prediction

```{r }
x<-data.frame(5.1,3.5,1.4,0.2,NA)
names(x)<-c("SepLen", "SepWid","PetLen","PetWid","Species")
pred_species<-predict(mynn, x, type = "class")
print(pred_species)
```